apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
spec:
  ingressClassName: ingress-internal
  rules:
  - host: sample.ce-82222875-sa.kubepia.net
    http:
      paths:
      - path: /
        backend:
          service:
            name: prod-cloud-sample
            port:
              number: 8080
        pathType: Prefix
