configMapGenerator:
- files:
  - application.yml
  name: cloud-sample-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: ce82222875acr.azurecr.io/cloud-sample
  newTag: "202411261835"
- name: cepgstapacr.azurecr.io/cloud-sample
  newTag: "202411261640"
